modLoader="javafml"
loaderVersion="[37,)"
license="EPL-1.0"
issueTrackerURL="https://github.com/iGoodie/TwitchSpawn/issues"

[[mods]]
modId="twitchspawn"
version="${file.jarVersion}"
displayName="TwitchSpawn"
authors="iGoodie"
logoFile="pack.png"
description='''
    TwitchSpawn listens for live events related to your Twitch channel using various Socket APIs.
    Then it handles those events with the rules handcrafted by you!
'''

[[dependencies.twitchspawn]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.twitchspawn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,)"
    ordering="NONE"
    side="BOTH"
